title: Jude WebCrafts Portfolio
logo: /assets/images/logo.png
description: A portfolio showcasing web design projects by Jude Odeda
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
